name: scoreup_app
description: A gamified way to study.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  google_sign_in: ^6.1.2
  flutter_svg: ^2.0.6
  provider: ^6.0.5
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/